name: Scheduler

on:
  schedule:
    - cron:  "*/30 * * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install requirements.txt
      run: pip3 install -r requirements.txt

    - name: save json
      run: python3 main.py

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./data
        publish_branch: api
on:
  schedule:
    - cron:  "*/30 * * * *"
